### ISSUE TITLE
백엔드 염종섭 6주차 배포 과제 제출입니다.

### ISSUE THREAD

**Issue by YeomJongSeop** [likelion-Inha-12/YeomJongSeop#7]
1. 배포 인스턴스
<img width="1255" alt="image" src="https://github.com/likelion-Inha-12/YeomJongSeop/assets/71175665/2f2f5bf0-fa50-4bca-85ca-5281f0b4cb81">

2. 배포성공(탄력적 IP입력)
<img width="454" alt="image" src="https://github.com/likelion-Inha-12/YeomJongSeop/assets/71175665/f1baa0cb-6ae1-49a8-8a78-140e9cd1a8bf">

templates폴더에 html 간단하게 만들어봤습니다. 
탄력적IP주소: 15.165.80.7

**Comment by soozzang** [comment]
👍👍

**Comment by juwon0403** [comment]
와우 html까지.. 능력자로 인정드립니다b
수고하셨슴당!
